version: 2.1

orbs:
  node: circleci/node@4.5.1
  slack: circleci/slack@3.4.2
  aws-s3: circleci/aws-s3@1.0.15
  cypress: cypress-io/cypress@1.26.0
  percy: percy/agent@0.1.3
  docker: circleci/docker@1.6.0

executors:
  build-executor:
    docker:
      - image: 449290502274.dkr.ecr.eu-west-2.amazonaws.com/wordpress-testing-site:0.1.0
        environment:
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_HOST: mysql:3306
          CYPRESS_baseUrl: http://localhost:80
      - image: 449290502274.dkr.ecr.eu-west-2.amazonaws.com/wordpress-testing-site-db:0.1.0
        environment:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    environment:
      PERCY_PARALLEL_NONE: $CIRCLE_JOB
      PERCY_PARALLEL_TOTAL: -1

commands:
  add_fingerprint:
    parameters:
      fingerprint:
        type: string
    steps:
      - add_ssh_keys:
          fingerprints: << parameters.fingerprint >>
  setup_environment:
    description: "Export pipeline number as env var"
    parameters:
      version_path:
        type: string
        default: ./
    steps:
      - run:
          name: "Export build time env vars"
          command: |
            echo "export PIPELINE_NUM=<< pipeline.number >>" >> $BASH_ENV
            echo "export VERSION=$(cat << parameters.version_path >> | grep '\"Version\":' | sed -e 's/ \* Version:           //')" >> $BASH_ENV
  jobstatus:
    description: "Send customised status messages to Slack"
    steps:
      - slack/status:
          failure_message: ':red_circle: ${CIRCLE_JOB} job of pipeline ${PIPELINE_NUM} for ${CIRCLE_TAG:-$CIRCLE_BRANCH} by ${CIRCLE_USERNAME} has failed'
          success_message: ':bananadance: ${CIRCLE_JOB} job of pipeline ${PIPELINE_NUM} for ${CIRCLE_TAG:-$CIRCLE_BRANCH} by ${CIRCLE_USERNAME} has passed'
  git_config:
    parameters:
      email:
        type: string
      author:
        type: string
    steps:
      - run:
          name: git configuration
          command: |
            git config --global user.email << parameters.email >>
            git config --global user.name << parameters.author >>
            ssh-keyscan github.com >> ~/.ssh/known_hosts
  git_tag:
    description: "Tag the project"
    parameters:
      tag:
        type: string
      when:
        type: string
        default: on_success
    steps:
      - run:
          name: Git tag
          command: |
            git tag -f << parameters.tag >>
          when: << parameters.when >>
  git_push_tags:
    description: "Push tags to remote repository"
    steps:
      - run:
          name: git push tags
          command: git push -f --tags

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - setup_environment:
          version_path: ./w3w-autosuggest/w3w-autosuggest.php
      - run: apt-get -yqq install mysql\*
      - node/install
      - node/install-packages:
          app-dir: ./test
      - run: cp -r w3w-autosuggest /var/www/html/wp-content/plugins/3-word-address-validation-field
      - persist_to_workspace:
          root: .
          paths: 
            - ./
      # - jobstatus
  tag:
    executor: build-executor
    steps:
      - checkout
      - add_fingerprint:
          fingerprint: "3a:f1:b4:f8:ea:43:76:68:8e:c0:f6:6c:09:d3:e9:14"
      - setup_environment
      - git_config:
          email: circleci@what3words.com
          author: $CIRCLE_USERNAME
      - git_tag:
          tag: v$VERSION
      - git_push_tags

workflows:
  build-and-test:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - TT-3715
      - cypress/run:
          executor: build-executor
          requires: 
            - build
          attach-workspace: true
          command: cd test && npx cypress run
          wait-on: 'http://localhost:80'
