name: Tagged release

on:
  pull_request:
    branches:
      - TT-9616
  push:
    branches:
      - TT-9616
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    name: Publish to SVN
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install subversion -y
      - run: |
          svn co https://plugins.svn.wordpress.org:443/3-word-address-validation-field /svn --trust-server-cert --non-interactive
