name: Tagged release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    name: Publish to SVN
    runs-on: ubuntu-latest
    steps:
      - name: Install SVN
        run: |
          sudo apt-get install subversion -y
      - uses: actions/checkout@v4
      - name: Checkout from Wordpress SVN
        run: |
          svn co https://plugins.svn.wordpress.org:443/3-word-address-validation-field ~/svn --trust-server-cert --non-interactive
      - name: Copy to assets
        run: |
          cp -r ./assets/* ~/svn/assets
      - name: Copy to trunk
        run: |
          cp -r ./w3w-autosuggest/* ~/svn/trunk
      - name: Create a release from ${{ github.ref_name }}
        run: |
          svn cp ~/svn/trunk ~/svn/tags/release-${{ github.ref_name }} --trust-server-cert --non-interactive
      - name: Commit changes to SVN
        run: |
          pushd ~/svn
          svn ci -m "${VERSION} release" --username "${{ vars.WP_SVN_USERNAME }}" --password "${{ secrets.WP_SVN_PASSWORD }}" --trust-server-cert --non-interactive
          popd
