name: Tagged release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    name: Publish to SVN
    runs-on: ubuntu-latest
    steps:
      - name: Install SVN
        run: |
          sudo apt-get install subversion -y
      - uses: actions/checkout@v4
      - name: Checkout from Wordpress SVN
        run: |
          svn co https://plugins.svn.wordpress.org:443/3-word-address-validation-field ~/svn --trust-server-cert --non-interactive
      - name: Copy to assets
        run: |
          cp -r ./assets/* ~/svn/assets
      - name: Copy to trunk
        run: |
          cp -r ./w3w-autosuggest/* ~/svn/trunk
      # - name: Copy to tag
      #   run: |
      #     svn cp ~/svn/trunk ~/svn/tags/release-$GITHUB_REF_NAME --trust-server-cert --non-interactive
      - name: Debug
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          ls .
          pwd
