name: Pull request

on:
  pull_request:
jobs:
  test:
    name: Run cypress tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE }}
          aws-region: eu-west-2
          mask-aws-account-id: 'true'
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - run: |
          docker compose -f ./docker-compose.test.yaml up -d
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix ./test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./test
          browser: chrome
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: ./test/cypress/screenshots/**/*.png
          if-no-files-found: ignore
      - name: Upload videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Recordings
          path: ./test/cypress/videos/**/*.mp4
          if-no-files-found: ignore
