name: Pull request

on:
  pull_request:
jobs:
  test:
    name: Run cypress tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE }}
          aws-region: eu-west-2
          mask-aws-account-id: 'true'
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - run: |
          docker compose -f ./docker-compose.test.yaml up -d
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - run: npm install --prefix ./test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./test
          browser: chrome
