name: Pull request

on:
  pull_request:
jobs:
  test:
    name: Run cypress tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          docker compose -f ./docker-compose.yaml up -d
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix ./test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./test
          browser: chrome
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: ./test/cypress/screenshots/**/*.png
          if-no-files-found: ignore
      - name: Upload videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Recordings
          path: ./test/cypress/videos/**/*.mp4
          if-no-files-found: ignore

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
